<?php
/**
 * File description.
 *
 * @package Frontity_Headtags
 */

/**
 * Class that contains the main behavior.
 */
class Frontity_Headtags {
	/**
	 * Prefix used in transients.
	 *
	 * @access  private
	 * @var     string
	 */
	private $transient_prefix = 'frontity_headtags_';

	/**
	 * Variable to store the original WP Query object (needed to restore it).
	 *
	 * @access  private
	 * @var     array
	 */
	private $query_backup = array();

	/**
	 * Integrations.
	 *
	 * @access  private
	 * @var     array
	 */
	private $integrations = array();

	/**
	 * Initialize the class and set its properties.
	 */
	public function __construct() {
		$this->load_dependencies();
		$this->define_public_hooks();
		$this->setup_integrations();
	}

	/**
	 * Load dependencies.
	 */
	public function load_dependencies() {
		// Directory name.
		$dirname = dirname( __FILE__ );
		// Hooks.
		require_once "$dirname/hooks/class-frontity-headtags-post-type-hooks.php";
		require_once "$dirname/hooks/class-frontity-headtags-taxonomy-hooks.php";
		require_once "$dirname/hooks/class-frontity-headtags-author-hooks.php";
		// Integrations.
		require_once "$dirname/integrations/class-frontity-headtags-yoast.php";
	}

	/**
	 * Register all hooks.
	 */
	public function define_public_hooks() {
		// Init classes.
		$post_types = new Frontity_Headtags_Post_Type_Hooks( $this );
		$taxonomies = new Frontity_Headtags_Taxonomy_Hooks( $this );
		$authors    = new Frontity_Headtags_Author_Hooks( $this );

		// Init hooks.
		if ( is_admin() ) {
			$post_types->register_admin_hooks();
			$taxonomies->register_admin_hooks();
			$authors->register_admin_hooks();
		} else {
			$post_types->register_rest_hooks();
			$taxonomies->register_rest_hooks();
			$authors->register_rest_hooks();
		}
	}

	/**
	 * Load integrations like Yoast, etc.
	 */
	public function setup_integrations() {
		$this->integrations = array(
			new Frontity_Headtags_Yoast(),
		);
	}


	/**
	 * Get cached head tags if found.
	 *
	 * @param string $transient_key Transient key.
	 * @return array|mixed
	 */
	public function get_cached_headtags( $transient_key ) {
		return get_transient( $this->transient_prefix . $transient_key );
	}

	/**
	 * Set cached head tags for this key.
	 *
	 * @param string      $transient_key Transient key.
	 * @param array|mixed $headtags Head tags to cache.
	 * @return bool
	 */
	public function set_cached_headtags( $transient_key, $headtags ) {
		return set_transient( $this->transient_prefix . $transient_key, $headtags, MONTH_IN_SECONDS );
	}

	/**
	 * Set cached head tags for this key.
	 *
	 * @param string $transient_key Transient key.
	 * @return bool
	 */
	public function delete_cached_headtags( $transient_key ) {
		return delete_transient( $this->transient_prefix . $transient_key );
	}

	/**
	 * Fetch yoast meta and possibly json ld and store in transient if needed
	 *
	 * @param string       $key Transient key.
	 * @param string|array $query URL query string or array of vars.
	 * @return array|mixed
	 */
	public function get_headtags( $key, $query ) {
		// Get head tags from transients.
		$headtags = $this->get_cached_headtags( $key );

		// If head tags are not cached, compute and cache them.
		if ( empty( $headtags ) ) {
			$headtags = $this->compute_headtags( $query );
			$this->set_cached_headtags( $key, $headtags );
		}
		// Return the head tags obtained.
		return $headtags;
	}

	/**
	 * Fetch yoast meta and possibly json ld and store in transient if needed
	 *
	 * @param string|array $query_vars URL query string or array of vars.
	 * @return array|mixed
	 */
	public function compute_headtags( $query_vars ) {
		$this->backup_query();
		$this->replace_query( $query_vars );

		ob_start();
		do_action( 'wp_head' );
		$html = ob_get_clean();
		$html = html_entity_decode( $html ); // Replaces &hellip; to ...
		$html = preg_replace( '/&(?!#?[a-z0-9]+;)/', '&amp;', $html ); // Replaces & to '&amp;.

		// Parse the xml to create an array of meta items.
		$headtags = $this->parse( $html );

		$this->restore_query();

		return $headtags;
	}


	/**
	 * Parse HTML to an array of meta key/value pairs using DOMDocument.
	 *
	 * @param string $html The HTML as generated by Yoast SEO.
	 *
	 * @return array An array containing all meta key/value pairs.
	 */
	private function parse( $html ) {
		// phpcs:disable WordPress.NamingConventions.ValidVariableName.UsedPropertyNotSnakeCase

		$headtags = array();

		$dom = new DOMDocument();
		$dom->loadHTML( mb_convert_encoding( $html, 'HTML-ENTITIES', 'UTF-8' ) );
		$nodes = $dom->getElementsByTagName( 'head' )[0]->childNodes;
		foreach ( $nodes as $node ) {

			// Ignore comments, texts, etc.
			if ( get_class( $node ) !== 'DOMElement' ) {
				continue;
			}

			// Create the tag object.
			$head_tag = array(
				'tag' => $node->tagName,
			);

			// Add attributes.
			if ( $node->hasAttributes() ) {
				$head_tag['attributes'] = array();
				foreach ( $node->attributes as $attr ) {
					$head_tag['attributes'][ $attr->nodeName ] = $attr->nodeValue;
				}
			}

			// Add content.
			if ( '' !== $node->textContent ) {
				$head_tag['content'] = $node->textContent;
			}

			// Append this tag to response if valid.
			if ( ! (
				$this->is_javascript( $head_tag ) ||
				$this->is_style( $head_tag )
			) ) {
				$headtags[] = $head_tag;
			}
		}

		return $headtags;
		// phpcs:enable
	}

	/**
	 * Check if a tag is JavaScript tag.
	 *
	 * @param Array $head_tag Object with the tag data.
	 *
	 * @return bool TRUE if it's a JavaScript script tag.
	 */
	private function is_javascript( $head_tag ) {
		return 'script' === $head_tag['tag'] && (
			! isset( $head_tag['attributes'] ) ||
			! isset( $head_tag['attributes']['type'] ) ||
			( in_array(
				$head_tag['attributes']['type'],
				array( '', 'text/javascript', 'application/javascript' ),
				true
			) )
		);
	}

	/**
	 * Check if a tag is a style tag or a stylesheet.
	 *
	 * @param Array $head_tag Object with the tag data.
	 *
	 * @return bool TRUE if it's a style tag or a stylesheet.
	 */
	private function is_style( $head_tag ) {
		return 'style' === $head_tag['tag'] || (
			'link' === $head_tag['tag'] &&
			'stylesheet' === $head_tag['attributes']['rel']
		);
	}

	/**
	 * Backup current query.
	 *
	 * @access private
	 */
	private function backup_query() {
		global $wp_query, $wp_the_query;
		// Store current values.
		array_push(
			$this->query_backup,
			array(
				'wp_query'     => $wp_query,
				'wp_the_query' => $wp_the_query,
			)
		);

	}

	/**
	 * Replace current query by the given one.
	 *
	 * @param string|array $query_vars URL query string or array of vars.
	 * @access private
	 */
	private function replace_query( $query_vars ) {
		global $wp_query, $wp_the_query;

		// Create an emtpy query.
		$new_query = new WP_Query();

		// Query elements using $query_vars.
		$new_query->query( $query_vars );

		// If $query_vars is empty, that means it's the home query.
		if ( empty( $query_vars ) ) {
			$new_query->is_home = true;
		}

		// phpcs:disable WordPress.WP.GlobalVariablesOverride.Prohibited
		$wp_query     = $new_query;
		$wp_the_query = $new_query;
		// phpcs:enable

		// Init integrations.
		foreach ( $this->integrations as $integration ) {
			$integration->init();
		}
	}

	/**
	 * Reset postdata and wp_query to previous values.
	 *
	 * @access private
	 */
	private function restore_query() {
		global $wp_query, $wp_the_query;
		$backup = array_pop( $this->query_backup );
		// phpcs:disable WordPress.WP.GlobalVariablesOverride.Prohibited
		$wp_query     = $backup['wp_query'];
		$wp_the_query = $backup['wp_the_query'];
		// phpcs:enable
		wp_reset_postdata();

		// Reset integrations.
		foreach ( $this->integrations as $integration ) {
			$integration->reset();
		}
	}
}
